clientConfig:
    maxConnTotal:    1000
    maxConnPerRoute: 1000
    ignoreSslErrors: true
    userAgent:       Mozilla/5.0 (compatible; AppDynamics UrlMonitor; http://www.appdynamics.com/)

defaultParams:
    method:          GET
    socketTimeout:   30000
    connectTimeout:  30000
    numAttempts:     1


#Sites that need to be monitored

sites:

  - name:     Google
    url:      http://www.google.com
    matchPatterns:
    - name: LuckyButton
      type: caseInsensitiveSubstring
      pattern: I'm Feeling Lucky

  - name:     AppDynamics
    url:      http://www.appdynamics.com

  - name:     File Download
    url:      https://github.com/Appdynamics/url-monitoring-extension/releases/download/1.0.6/UrlMonitor.zip

  - name:     My Controller
    url:      http://localhost:8090/controller/rest/applications
    username: user1@customer1
    password: welcome
    connectTimeout: 60000


#prefix used to show up metrics in AppDynamics
#This will create it in specific Tier. Replace
#metricPrefix: Server|Component:<TierID>|Custom Metrics|URLMonitor|
#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|URLMonitor|

