clientConfig:
    maxConnTotal:    1000
    maxConnPerRoute: 1000
    ignoreSslErrors: true
    userAgent:       Mozilla/5.0 AppDynamics-UrlMonitor/1.0.6

defaultParams:
    method:          GET
    socketTimeout:   30000
    connectTimeout:  30000
    numAttempts:     3

#Sites that need to be monitored
sites:

- name:     Google
  url:      http://www.google.com
  expect:
  - substring: Mail

- name:     AppDynamics
  url:      https://www.appdynamics.com

- name:     Help
  url:      https://help.appdynamics.com

- name:     My Controller
  url:      https://localhost:8080/controller/rest/applications
  username: user1@customer1
  password: welcome
  connectTimeout: 60000
